#!/usr/xbin/bash
 a="\033[30;1m"
 m="\033[31;1m"
 h="\033[32;1m"
 k="\033[33;1m"
 b="\033[34;1m"
 c="\033[35;1m"
 pu="\033[36;1m"
 p="\033[37;1m"
 m1="\033[38;1m"
 p2="\033[39;1m"
 hi="\033[40;1m"
 clear
 s="\033[31;1m╔"
 t="\033[31;1m╗"
 u="\033[31;1m║"
 z="${m}════════════════════════════════"
 q="${m}════"
 j="${m}══════════"
 o="${m}╚"
 n="${m}╝"
 ulang="sh spam-sms.sh"
clear

echo "\033[031m   _________________      _____   .___ "
echo "\033[031m  /   _____/\_____  \    /     \  |   |"
echo "\033[032m  \_____  \  /   |   \  /  \ /  \ |   |"
echo "\033[032m  /        \/    |    \/    Y    \|   |"
echo "\033[033m /_______  /\_______  /\____|__  /|___|"
echo "\033[033m         \/         \/         \/      "
echo "   ${o}${z}${n}"
echo
echo "${k}<════════════════════════════════════════>"
echo "${p}[${h}01${p}] ${h}VIRUS 1"
echo "${p}[${h}02${p}] ${p}VIRUS 2"
echo "${p}[${h}03${p}] ${pu}VIRUS 3"
echo "${p}[${h}04${p}] ${b}VIRUS 4"
echo "${p}[${h}05${p}] ${c}VIRUS 5"
echo "${p}[${h}00${p}] ${m}CLOSE "
echo "${k}<════════════════════════════════════════>"
echo
echo "${p}"


read -p "[+] SELECT: " r
if [ $r = 01 ] || [ $r = 1 ];then
sleep 1
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[34;1mSTAR BOY"
sleep 2
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[34;1mLoading..."
sleep 2
cd virus
sh virtex1.sh
echo "${p}"
read -p "[+]Ulang Lagi y/t : " k
if [ $k = y ] || [ $k = Y ];then
sh virus.sh

elif [ $k = t ] || [ $k = T ];then
sh hek.sh
fi

elif [ $r = 02 ] || [ $r = 2 ];then
sleep 1
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[34;1mSedang Membuat Virtex..."
sleep 2
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[34;1mLoading..."
sleep 2
cd virus
sh virtex2.sh
echo "${p}"
read -p "[+]Ulang Lagi y/t : " k
if [ $k = y ] || [ $k = Y ];then
sh virus.sh

elif [ $k = t ] || [ $k = T ];then
sh hek.sh
fi

elif [ $r = 03 ] || [ $r = 3 ];then
sleep 1
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[34;1mSedang Membuat Virtex..."
sleep 2
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[34;1mLoading..."
sleep 2
cd virus
sh virtex3.sh
echo "${p}"
read -p "[+]Ulang Lagi y/t : " k
if [ $k = y ] || [ $k = Y ];then
sh virus.sh

elif [ $k = t ] || [ $k = T ];then
sh hek.sh
fi

elif [ $r = 04 ] || [ $r = 4 ];then
sleep 1
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[34;1mSedang Membuat Virtex..."
sleep 2
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[34;1mLoading..."
sleep 2
cd virus
sh virtex4.sh
echo "${p}"
read -p "[+]Ulang Lagi y/t : " k
if [ $k = y ] || [ $k = Y ];then
sh virus.sh

elif [ $k = t ] || [ $k = T ];then
sh hek.sh
fi


elif [ $r = 05 ] || [ $r = 5 ];then
sleep 1
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[34;1m........."
sleep 2
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[34;1mLoading..."
sleep 2
cd virus
sh virtex5.sh
echo
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[34;1mFINISH"
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[34;1mNOW COPY"
echo "\033[39;1m[\033[32;1m√\033[39;1m]\033[34;1mSHARE WHATSAAP"
echo "${p}"
read -p "[+]BACKy/t : " k
if [ $k = y ] || [ $k = Y ];then
sh virus.sh

elif [ $k = t ] || [ $k = T ];then
sh hek.sh
fi

elif [ $r = 06 ] || [ $r = 6 ];then
sh hek.sh

elif [ $r = 00 ] || [ $r = 0 ];then
sleep 1
echo "${b} Thanks You *_*"
exit

else 
echo
echo "${h}         ~ ~  ┌${p1}∩${h}┐${k}(${m}◣${p1}_${m}◢${k})${h}┌${p1}∩${h}┐  ~ ~"
echo "         ${p}[${m}!${p}]${m} pilihan salah ${p}[${m}!${p}]${k}"
echo
sleep 1
sh virus.sh
fi
